# Generated by Django 3.2.13 on 2022-06-08 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DrinkCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='MealCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('available_from', models.TimeField()),
                ('available_until', models.TimeField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_name', models.CharField(max_length=200, unique=True)),
                ('description', models.CharField(max_length=200)),
                ('dietary_info', models.TextField(blank=True)),
                ('allergy_info', models.TextField(blank=True)),
                ('price', models.FloatField()),
                ('is_available', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('meal_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.mealcategory')),
            ],
            options={
                'ordering': ['-is_available', '-meal_category'],
            },
        ),
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drink_name', models.CharField(max_length=200, unique=True)),
                ('description', models.CharField(max_length=200)),
                ('dietary_info', models.TextField(blank=True)),
                ('allergy_info', models.TextField(blank=True)),
                ('price', models.FloatField()),
                ('is_available', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('drink_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.drinkcategory')),
            ],
            options={
                'ordering': ['-is_available', '-drink_category'],
            },
        ),
    ]
