# Generated by Django 3.2.13 on 2022-06-08 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='meal_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_category', to='menu.mealcategory'),
        ),
    ]
