# Generated by Django 3.2.13 on 2022-06-14 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_meal_meal_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mealcategory',
            options={'verbose_name_plural': 'meal_categories'},
        ),
        migrations.AlterField(
            model_name='meal',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
