# Generated by Django 3.2.13 on 2022-06-14 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20220614_1013'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beverage_name', models.CharField(max_length=200, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('drink_type', models.IntegerField(choices=[(0, 'non-alcoholic drinks'), (1, 'alcoholic drinks'), (2, 'hot drinks'), (3, 'add new')], default=1)),
                ('price', models.FloatField()),
                ('is_available', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_available'],
            },
        ),
    ]
