# Generated by Django 3.2.13 on 2022-06-14 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_beverage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Beverage',
        ),
        migrations.AddField(
            model_name='drinkcategory',
            name='drink_type',
            field=models.CharField(choices=[('AL', 'Alcoholic drink'), ('NAL', 'Non-alcoholic drink'), ('HOT', 'Hot drink')], default='AL', max_length=3),
        ),
    ]
