# Generated by Django 3.2.13 on 2022-06-19 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_auto_20220614_1143'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drinkcategory',
            options={'verbose_name_plural': 'drink categories'},
        ),
        migrations.AlterModelOptions(
            name='mealcategory',
            options={'verbose_name_plural': 'meal categories'},
        ),
        migrations.AlterField(
            model_name='drink',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
