# Generated by Django 3.2.13 on 2022-06-22 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_auto_20220619_1315'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MealCategory',
            new_name='Category',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='drinkcategory',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='meal',
            options={'ordering': ['-is_available', '-category']},
        ),
        migrations.RemoveField(
            model_name='drinkcategory',
            name='description',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='meal_category',
        ),
        migrations.AddField(
            model_name='meal',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='menu.category'),
            preserve_default=False,
        ),
    ]
