# Generated by Django 3.2.13 on 2022-10-03 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_alter_meal_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='drink_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drinks', to='menu.drinkcategory'),
        ),
    ]
