# Generated by Django 3.2.13 on 2022-06-19 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=50, unique=True)),
                ('seat_capacity', models.IntegerField(default=2)),
                ('position', models.CharField(blank=True, max_length=200)),
                ('available', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-available'],
            },
        ),
    ]
