# Generated by Django 3.2.13 on 2022-06-19 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0006_reservation_party_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='reservation_code',
        ),
    ]
