# Generated by Django 3.2.13 on 2022-10-07 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0007_remove_reservation_reservation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='special_requirement',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
